version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_NUMBER: ${TWILIO_NUMBER}
      HOST: ${HOST}
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
    ports:
      - 9999:9999
    command: npm run dev
    depends_on:
      - db
    restart: always


  db:
    image: postgres:latest
    restart: always
    ports:
      - 6432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local